### ISSUE TITLE
crate/barrel issues

### ISSUE THREAD

**Issue by carpenteer** [Asetia-Lux/VALKEA#2]
small and large crate and barrel have broken/unlocalized names and are swapped - large refers to the smaller model in both cases.

**Comment by Asetia-Lux** [comment]
Will also address, ty.

**Comment by carpenteer** [comment]
Both crates are still labeled "Small Crate"

**Comment by Asetia-Lux** [comment]
:sweat_smile:
Idk why it did not update or save when I edited the first time.
But staring at edit now.
Will be updated next version/patch.

thanks for letting me know
