### ISSUE TITLE
1.0.0 Destroying Iron Scale Dupes Iron Bars

### ISSUE THREAD

**Issue by mfinite8088** [Asetia-Lux/VALKEA#3]
Crafting the Iron Scale costs 1 iron bar.

If you destroy the Iron Scale, you get your iron bar back, but the Iron Scale remains.

Keep destroying the Iron Scale until you have all of the iron bars you want.

![iron](https://user-images.githubusercontent.com/100739383/160700638-12d206b5-7cc2-46c0-b6a4-8368e88b11af.JPG)

**Comment by Asetia-Lux** [comment]
Already been addressed, will no longer be an issue when updated.
