### ISSUE TITLE
I will add this to help

### ISSUE THREAD

**Issue by xHadesSoulx** [Asetia-Lux/VALKEA#4]
items that are bugged 

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
(wrapper dynamic-method) Piece.DMD<Piece::DropResources>(Piece)
WearNTear.Destroy () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
WearNTear.RPC_Remove (System.Int64 sender) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
RoutedMethod.Invoke (System.Int64 rpc, ZPackage pkg) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
ZNetView.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData rpcData) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
ZNetView.InvokeRPC (System.String method, System.Object[] parameters) (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
WearNTear.Remove () (at <dcb0de0155834d459f18d7ac6ea5244b>:0)
(wrapper dynamic-method) Player.DMD<Player::RemovePiece>(Player)
(wrapper dynamic-method) Player.DMD<Player::UpdatePlacement>(Player,bool,single)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

loose Messy Hay
iron Scales
unknow silver setting
A singular Sausage
Bloodied Laundry Line

**Comment by Asetia-Lux** [comment]
Now should be fixed.
