### ISSUE TITLE
Organ breaks and spawns drops elsewhere

### ISSUE THREAD

**Issue by cougarten** [Asetia-Lux/VALKEA#5]
If I try to place the organ "upstairs" in my stone building it just despawns. The material can be found ~10-20 meters off.

Could it be it registers at the wrong place and thinks it's hanging in the air?

**Comment by Asetia-Lux** [comment]
Ill will have to test.
Next time it happens please check logoutput for errors or warnings, if any please share.

**Comment by Asetia-Lux** [comment]
Ok, was able to recreate issue.
Likely a collider issue or wnt issue, i will look into when I have the chance.

**Comment by cougarten** [comment]
Oh cool, sorry I didn't get to reproduce it earlier.
Thanks so much for VALKEA, it's fun :)

**Comment by Asetia-Lux** [comment]
Its is aye-ok.
There were no errors or anything. So you wouldnt have found any :P

**Comment by Asetia-Lux** [comment]
Ok so not great news.
I am currently unsure why it is doing this.
It has yet to be fixed in v1.2.0 BUT will continue to try to figure it out.
I think it has to do with the colliders so i will keep fiddling!

**Comment by cougarten** [comment]
We'll be patient!

listening to some dj shadow
https://youtu.be/sO5PCru_Z-E?list=RDsO5PCru_Z-E&t=128

while having a bath where the organ is supposed to go in the future
![image](https://user-images.githubusercontent.com/7131556/164889765-fae0f19e-d8f0-4e8d-9d03-c263710abb2a.png)

**Comment by Asetia-Lux** [comment]
OOOO look nice.
Would you be upset if organ was a different model?

I think its cursed lol

**Comment by cougarten** [comment]
We don't discriminate against different organ types in our base :). Every organ will make us happy.

**Comment by Asetia-Lux** [comment]
ok new organ is available in 1.3.0
I was unable to test it on a second floor setting, but im sure youll let me know

**Comment by cougarten** [comment]
Amaaaaazing :) even prettier than the old one!

![image](https://user-images.githubusercontent.com/7131556/165987640-2838d539-9ee0-45c4-aa1a-c19ea5526fa1.png)
