### ISSUE TITLE
Issues on 26 Degree Corners

### ISSUE THREAD

**Issue by MidwestJen** [Asetia-Lux/VALKEA#6]
I haven't tested it on any other pieces, but I can say that the 26 degree corner pieces aren't snapping. They're also unable to stay in the air, immediately disintegrating upon placement. I rolled mine back to the previous version (since those were pretty important in my roof, LOL), so can't test the others, but thought I'd let you know.

Also? This is one of my favorite build addons. I can't say I care for the IKEA bright n shiny desks, etc but the Sheawood Pieces are fantastic and dye (with the Comfy Colorful Pieces) pretty well. Bravo! <3

**Comment by Asetia-Lux** [comment]
Thanks Jen!

Yes this has been brought up and im looking into it!
